import Head from 'next/head'
import Image from 'next/image'
import Header from './Header'

export default function Home() {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <Header />

            <main className="max-w-7xl mx-auto px-4 sm:px-6">

            </main>

            <footer>

            </footer>
        </div>
    )
}
